include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_final_locals: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
