import 'package:flutter/material.dart';

class LanguageManager extends InheritedNotifier<ValueNotifier<Locale>> {
  LanguageManager({
    required ValueNotifier<Locale> notifier,
    required super.child,
    super.key,
  }) : super(notifier: notifier);

  static LanguageManager of(BuildContext context) {
    final manager =
        context.dependOnInheritedWidgetOfExactType<LanguageManager>();
    assert(manager != null, 'LanguageManager not found in context');
    return manager!;
  }

  Locale get locale => notifier!.value;

  void setLocale(Locale locale) => notifier!.value = locale;

  TextDirection get direction =>
      locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  String t(String key) {
    final lang = locale.languageCode;
    final translations = _translations[lang] ?? _translations['en']!;
    return translations[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'SouqBid',
      'next': 'Next',
      'start_now': 'Start now',
      'onboarding_title_1': 'Welcome to SouqBid',
      'onboarding_sub_1': 'A refined marketplace for inspired auctions.',
      'onboarding_title_2': 'Bid with confidence',
      'onboarding_sub_2': 'Track prices, trends, and stories instantly.',
      'onboarding_title_3': 'Begin your journey',
      'onboarding_sub_3': 'Create your account and unlock curated deals.',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as Guest',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'invalid_email': 'Please enter a valid email.',
      'invalid_password':
          'Password should be 8+ characters with letters and numbers.',
      'password_mismatch': 'Passwords do not match.',
      'welcome_back': 'Welcome back',
      'hello_guest': 'Hello guest',
      'home': 'Home',
      'offers': 'Offers',
      'wanted': 'Wanted',
      'profile': 'Profile',
      'bids': 'Bids',
      'purchases': 'Purchases',
      'search_items': 'Search items',
      'nearest': 'Nearest',
      'ending_soon': 'Ending soon',
      'highest_discount': 'Highest discount',
      'ai_chips': 'AI Insights',
      'current_bid': 'Current bid',
      'time_left': 'Time left',
      'bid_now': 'Bid Now',
      'place_bid': 'Place Bid',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'bid_too_low': 'Please enter a bid higher than the current amount.',
      'bid_success': 'Bid placed successfully!',
      'offers_title': 'Offers & Deals',
      'switch_to_list': 'Switch to list',
      'switch_to_grid': 'Switch to grid',
      'no_offers': 'No offers available now.',
      'wanted_title': 'Wanted Items',
      'all_requests': 'All Requests',
      'my_requests': 'My Requests',
      'add_request': 'Add Request',
      'title': 'Title',
      'target_price': 'Target Price',
      'city': 'City',
      'description': 'Description',
      'expires_at': 'Expires at',
      'save': 'Save',
      'invalid_form': 'Please complete required fields.',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark mode',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'guest': 'Guest',
      'light': 'Light',
      'dark': 'Dark',
      'auto': 'Auto',
      'favorites': 'Favorites',
      'remove': 'Remove',
      'no_favorites': 'No favorites yet.',
      'no_bids': 'No active bids yet.',
      'session_restored': 'Session restored',
      'pull_to_refresh': 'Pull to refresh auctions',
      'loading': 'Loading',
      'ending_in': 'Ending in',
      'minutes': 'm',
      'hours': 'h',
      'days': 'd',
      'seconds': 's',
    },
    'ar': {
      'app_name': 'SouqBid',
      'next': 'التالي',
      'start_now': 'ابدأ الآن',
      'onboarding_title_1': 'مرحباً بك في SouqBid',
      'onboarding_sub_1': 'منصة مزادات عصرية أنيقة.',
      'onboarding_title_2': 'زايد بثقة',
      'onboarding_sub_2': 'تابع الأسعار والاتجاهات فوراً.',
      'onboarding_title_3': 'ابدأ رحلتك',
      'onboarding_sub_3': 'أنشئ حسابك واستمتع بالعروض.',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'الدخول كزائر',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'invalid_email': 'الرجاء إدخال بريد إلكتروني صحيح.',
      'invalid_password':
          'يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على أرقام وحروف.',
      'password_mismatch': 'كلمتا المرور غير متطابقتين.',
      'welcome_back': 'مرحباً بعودتك',
      'hello_guest': 'أهلاً بالزائر',
      'home': 'الرئيسية',
      'offers': 'العروض',
      'wanted': 'الطلبات',
      'profile': 'الملف الشخصي',
      'bids': 'المزايدات',
      'purchases': 'المشتريات',
      'search_items': 'ابحث عن المنتجات',
      'nearest': 'الأقرب',
      'ending_soon': 'تنتهي قريباً',
      'highest_discount': 'أعلى خصم',
      'ai_chips': 'معلومة ذكية',
      'current_bid': 'السعر الحالي',
      'time_left': 'الوقت المتبقي',
      'bid_now': 'زايد الآن',
      'place_bid': 'تأكيد المزايدة',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'bid_too_low': 'يرجى إدخال قيمة أعلى من الحالية.',
      'bid_success': 'تم تقديم المزايدة بنجاح!',
      'offers_title': 'العروض والخصومات',
      'switch_to_list': 'عرض كقائمة',
      'switch_to_grid': 'عرض كشبكة',
      'no_offers': 'لا توجد عروض حالياً.',
      'wanted_title': 'الطلبات المطلوبة',
      'all_requests': 'كل الطلبات',
      'my_requests': 'طلباتي',
      'add_request': 'إضافة طلب',
      'title': 'العنوان',
      'target_price': 'السعر المستهدف',
      'city': 'المدينة',
      'description': 'الوصف',
      'expires_at': 'تاريخ الانتهاء',
      'save': 'حفظ',
      'invalid_form': 'يرجى إكمال الحقول المطلوبة.',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'logout': 'تسجيل الخروج',
      'guest': 'زائر',
      'light': 'فاتح',
      'dark': 'داكن',
      'auto': 'تلقائي',
      'favorites': 'المفضلة',
      'remove': 'إزالة',
      'no_favorites': 'لا توجد عناصر مفضلة.',
      'no_bids': 'لا توجد مزايدات حالياً.',
      'session_restored': 'تم استرجاع الجلسة',
      'pull_to_refresh': 'اسحب لتحديث المزادات',
      'loading': 'جاري التحميل',
      'ending_in': 'تنتهي خلال',
      'minutes': 'د',
      'hours': 'س',
      'days': 'ي',
      'seconds': 'ث',
    },
  };
}
