import 'package:flutter/material.dart';

class LanguageManager extends InheritedNotifier<ValueNotifier<Locale>> {
  LanguageManager({
    required ValueNotifier<Locale> localeNotifier,
    required super.child,
    super.key,
  })  : _localeNotifier = localeNotifier,
        super(notifier: localeNotifier);

  final ValueNotifier<Locale> _localeNotifier;

  static LanguageManager of(BuildContext context) {
    final manager =
        context.dependOnInheritedWidgetOfExactType<LanguageManager>();
    assert(manager != null, 'LanguageManager not found in context');
    return manager!;
  }

  Locale get locale => _localeNotifier.value;

  void switchLanguage() {
    final current = _localeNotifier.value.languageCode;
    _localeNotifier.value = current == 'en'
        ? const Locale('ar')
        : const Locale('en');
  }

  String t(String key) {
    final lang = _localeNotifier.value.languageCode;
    final translations = _translations[lang] ?? _translations['en']!;
    return translations[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'auction': 'Auction',
      'auction_app': 'Auction Hub',
      'welcome': 'Welcome to the future of bidding',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'discover_items': 'Discover premium items',
      'secure_payments': 'Secure, transparent bidding',
      'sell_anything': 'Sell anything in minutes',
      'back': 'Back',
      'appearance': 'Appearance',
      'invalid_alert': 'Please fill all fields with valid numbers.',
      'pick_image': 'Pick mock image',
      'image_selected': 'Mock image ready',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as Guest',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'invalid_email': 'Please enter a valid email.',
      'password_length': 'Password must be at least 6 characters.',
      'password_match': 'Passwords do not match.',
      'home': 'Home',
      'settings': 'Settings',
      'favorites': 'Favorites',
      'alerts': 'Alerts',
      'bids': 'My Bids',
      'sell_buy': 'Sell & Buy',
      'place_bid': 'Bid',
      'current_bid': 'Current Bid',
      'view_details': 'View details',
      'added_favorite': 'Added to favorites',
      'removed_favorite': 'Removed from favorites',
      'price': 'Price',
      'countdown': 'Countdown',
      'time_left': 'Time left',
      'description': 'Description',
      'bid_now': 'Bid now',
      'bid_success': 'Bid placed successfully!',
      'active_bids': 'Active bids',
      'no_bids': 'No active bids yet',
      'favorites_empty': 'No favorites yet',
      'alerts_empty': 'No alerts created yet',
      'add_alert': 'Add Alert',
      'add_item': 'Add item',
      'alert_title': 'Alert title',
      'min_price': 'Minimum price',
      'max_price': 'Maximum price',
      'create': 'Create',
      'sell': 'Sell',
      'buy': 'Buy',
      'sell_form_title': 'Item title',
      'sell_form_price': 'Desired price',
      'sell_form_desc': 'Add a short description',
      'buy_form_min': 'Target min price',
      'buy_form_max': 'Target max price',
      'submit': 'Submit',
      'theme': 'Theme',
      'dark_mode': 'Dark mode',
      'language': 'Language',
      'language_switched': 'Language updated',
      'theme_switched': 'Theme updated',
      'pull_refresh': 'Pull to refresh auctions',
      'guest': 'Guest',
      'logout': 'Logout',
      'welcome_back': 'Welcome back',
      'timer_finished': 'Auction finished',
      'seconds': 's',
      'minutes': 'm',
      'hours': 'h',
      'days': 'd',
      'price_range': 'Price range',
      'search_items': 'Search auctions, categories...',
      'empty_state': 'No items match your filters yet',
      'loading_more': 'Loading more lots...',
      'invalid_price': 'Please provide a valid price.',
      'item_created': 'New auction drafted locally',
    },
    'ar': {
      'auction': 'المزاد',
      'auction_app': 'منصة المزادات',
      'welcome': 'مرحبًا بك في مستقبل المزادات',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'discover_items': 'اكتشف أفضل السلع',
      'secure_payments': 'مزايدات آمنة وشفافة',
      'sell_anything': 'بع أي شيء خلال دقائق',
      'back': 'رجوع',
      'appearance': 'المظهر',
      'invalid_alert': 'يرجى تعبئة الحقول بشكل صحيح.',
      'pick_image': 'إرفاق صورة تجريبية',
      'image_selected': 'تم إرفاق صورة تجريبية',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'الدخول كزائر',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح.',
      'password_length': 'يجب ألا تقل كلمة المرور عن 6 أحرف.',
      'password_match': 'كلمتا المرور غير متطابقتين.',
      'home': 'الرئيسية',
      'settings': 'الإعدادات',
      'favorites': 'المفضلة',
      'alerts': 'التنبيهات',
      'bids': 'مزايداتي',
      'sell_buy': 'بيع وشراء',
      'place_bid': 'زايد الآن',
      'current_bid': 'أعلى مزايدة',
      'view_details': 'عرض التفاصيل',
      'added_favorite': 'تمت الإضافة إلى المفضلة',
      'removed_favorite': 'تمت الإزالة من المفضلة',
      'price': 'السعر',
      'countdown': 'العد التنازلي',
      'time_left': 'الوقت المتبقي',
      'description': 'الوصف',
      'bid_now': 'زايد الآن',
      'bid_success': 'تمت المزايدة بنجاح!',
      'active_bids': 'مزايدات نشطة',
      'no_bids': 'لا توجد مزايدات حالياً',
      'favorites_empty': 'لا توجد عناصر مفضلة',
      'alerts_empty': 'لم يتم إنشاء تنبيهات بعد',
      'add_alert': 'إضافة تنبيه',
      'add_item': 'إضافة منتج',
      'alert_title': 'عنوان التنبيه',
      'min_price': 'الحد الأدنى للسعر',
      'max_price': 'الحد الأعلى للسعر',
      'create': 'إنشاء',
      'sell': 'بيع',
      'buy': 'شراء',
      'sell_form_title': 'عنوان المنتج',
      'sell_form_price': 'السعر المطلوب',
      'sell_form_desc': 'أضف وصفًا قصيرًا',
      'buy_form_min': 'الحد الأدنى المطلوب',
      'buy_form_max': 'الحد الأعلى المطلوب',
      'submit': 'إرسال',
      'theme': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'language_switched': 'تم تحديث اللغة',
      'theme_switched': 'تم تحديث المظهر',
      'pull_refresh': 'اسحب لتحديث المزادات',
      'guest': 'زائر',
      'logout': 'تسجيل الخروج',
      'welcome_back': 'مرحبًا بعودتك',
      'timer_finished': 'انتهى المزاد',
      'seconds': 'ث',
      'minutes': 'د',
      'hours': 'س',
      'days': 'ي',
      'price_range': 'نطاق السعر',
      'search_items': 'ابحث في المزادات والفئات...',
      'empty_state': 'لا نتائج مطابقة للفلاتر',
      'loading_more': 'جاري تحميل المزيد...',
      'invalid_price': 'يرجى إدخال سعر صالح.',
      'item_created': 'تم إنشاء مزاد محليًا',
    },
  };
}
